<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>{% if page.title %}{{ page.title }} | {% endif %}{{ site.title }}</title>
    <meta name="description" content="{% if page.description %}{{ page.description }}{% else %}{{ site.description }}{% endif %}">

    <link rel='stylesheet' href="{{ "/theme/res/site.css" | prepend: site.baseurl }}" type="text/css">
    <script type="application/javascript" href="{{ "/theme/res/site.js" | prepend: site.baseurl }}"></script>
  </head>
  <body>
    <header>
      <div id="headerbar">
        <a href="{{ "/" | prepend: site.baseurl }}" title="{{ site.title }}"><span>Nouse</span><h1>{{ site.title }}</h1></a>
      </div>
      <nav id="primary-menu">
        <ul>
          {% for subpage in site.pages %}{% if subpage.level == "primary" %}
            <li><a href="{{ subpage.url | prepend: site.baseurl }}" title="{{ subpage.title }}">{{ subpage.title }}</a></li>
          {% endif %}{% endfor %}
        </ul>
      </nav>
      <nav id="secondary-menu">
        <ul>
          {% for article in site.pages %}{% if article.url contains page.url and article.level == "secondary" and page.url != "/" %}
            <li><a href="{{ article.url | prepend: site.baseurl }}" title="{{ article.title }}">{{ article.title }}</a></li>
          {% endif %}{% endfor %}
        </ul>
      </nav>
    </header>
    <div class="content">
